const router = require('express').Router();
const {getReport, getReports, getPatient,getPatientCard, setPatient, getPatients, getOldageHomeInfo, count} = require('./controllers/get_set')
const {logincaretaker, checksession,deletesession} = require('./controllers/sessions')
const {uploadpdf} = require('./controllers/LLM')
router.get('/getreport', getReport)
router.get('/getreports', getReports)
router.post('/setPatient',setPatient)
router.get('/getpatient', getPatient)
router.get('/getpatientcard', getPatientCard)
router.get('/getpatients', getPatients)
router.get('/getoldagehomeinfo', getOldageHomeInfo)
router.post('/upload', uploadpdf)
router.get('/count', count)
router.post('/logincaretaker', logincaretaker)
router.get('/checksession', checksession)
router.post("/deletesession",deletesession)
module.exports = router